import Footer from './components/Footer'
import HireMe from './components/HireMe'
import NavBar from './components/NavBar'
import './globals.css'
import { Montserrat } from 'next/font/google'

const mont = Montserrat({
	subsets: ['latin'],
	variable: '--mont',
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${mont.variable} font-sans flex flex-col min-h-screen`}
			>
				<HireMe />
				<NavBar />
				{children}
				<Footer />
			</body>
		</html>
	)
}
